name: ffmpegcrop
synopsis: Crop a video using ffmpeg
license-file: LICENSE
dependencies:
  - base
  - turtle
  - cmdargs
  - text
  - gloss
  - lens
  - generic-lens

tested-with:
  GHC==9.8.2

executable:
  main:
    main.hs
  ghc-options:
    -threaded
